name: publish-to-npm2
on:
  release:
    types: [published]
  push:
    branches: [ test-npm2 ]
jobs:
  release-npm:
    runs-on: ubuntu-20.04
    environment: build
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip npm]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node and npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/
      - run: npm install shelljs
      - run: npm install -g @jsdevtools/npm-publish
      - name: build
        env:
          token: ${{secrets.NPM_TOKEN}}
        run: node build/bin/publish-electerm-react.js
