name: Publish to WinGet
on:
  release:
    types: [released]
  push:
    branches: [ test-winget ]
jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: build
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: electerm.electerm
          installers-regex: 'win-x64-installer.exe$'
          max-versions-to-keep: 10
          token: ${{ secrets.WINGET_TOKEN }}
